/// Flutter icons Kebab_icon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Kebab_icon
///      fonts:
///       - asset: fonts/Kebab_icon.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Kebab_icon {
  Kebab_icon._();

  static const _kFontFam = 'Kebab_icon';
  static const String? _kFontPkg = null;

  static const IconData Kebab =
      IconData(0xea1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
